services:
  - type: web
    name: recipe-book-api
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/taka87/recipe-book-api
    branch: main
    rootDir: .
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production